### PR TITLE
https://tracker.moodle.org/browse/MDL-49643

### PR DESCRIPTION
**Pull request by dmonllao**

### CODE REVIEW

**Comment by dmonllao** [comment]
Grr, not valid, we should "if it", otherwise I'm afraid we will still see the debugging message.

**Comment by dmonllao** [comment]
I've updated patch to 43b2227cc4e53396f33622e9eb0c840c8c721c7a and tested in master (2015041700.00) and 2.8 (2014111005.08)

**Comment by dmonllao** [comment]
Same patch than before but with amended commit msg a24cb1f9626dabed31ba12f9cda538833a5c6bdf, same branch.

**Comment by dmonllao** [comment]
Patch updated after integration chat discussion: ffd8aaefd55c716bed5c3c7ca058bb9c793aafe1

**Comment by danpoltawski** [comment]
Please could you update the commit message :)

**Comment by stronk7** [comment]
and here you get the award for the "Most amended commit in 2015", LOL. Thanks David!

**Comment by dmonllao** [comment]
lol, done.

**Comment by danpoltawski** [comment]
Merged, thanks

**Pull request merged**
