### PR TITLE
Move to moodle-plugin-ci v3

### PR DESCRIPTION
**Pull request by stronk7**
Not much to say. just bump to v3 and ensure PRs are working ok against travis-ci.com

### CODE REVIEW

**Review by danpoltawski — APPROVED** [review]
+1

**Comment by danpoltawski** [comment]
Except it fails 😅

**Comment by stronk7** [comment]
Heh, yeah, it was already before the bump, I think. Hi!

**Comment by stronk7** [comment]
Have added one more commit getting rid of all PHP and CSS styling errors.

**Comment by stronk7** [comment]
Note that #11 has been created because @ https://github.com/moodlehq/moodle-plugin-ci/issues/45 it was detected that the old/legacy YUI directory structure was the cause of the "Unable to find local grunt" errors here.

So, surely we can go ahead with this now, with #11 fixing the situation for the plugin.

**Comment by stronk7** [comment]
Ok, I'm going to merge this now, https://github.com/moodlehq/moodle-plugin-ci/issues/46 has been already merged, so next moodle-plugin-ci won't fail with this case. Plus we have #11 to move away from legacy YUI dirs here.

**Pull request merged**
